### ISSUE TITLE
files/.public is not ignored

### ISSUE THREAD

**Issue by fritzmg** [contao/contao#286]
**Affected version(s)**
4.4.33, 4.6.13

**Description**  
Usually, only sub folders of `files` can be made public by putting a `.public` file there. However, if you manually create a `files/.public` file and run `contao:symlinks`, `files/` will by symlinked to `web/files` and you'll get the following error for every sub folder that was already "public" before: 
```
 ------- ------------------------ ----------------------------------------------------------------
          Symlink                  Target / Error
 ------- ------------------------ ----------------------------------------------------------------
  OK      web/files                files
  ERROR   web/files/public         The path "web/files/public" exists and is not a symlink.
  OK      system/themes/flexible   vendor/contao/core-bundle/src/Resources/contao/themes/flexible
  OK      web/assets               assets
  OK      web/system/themes        system/themes
  OK      system/logs              var/logs
 ------- ------------------------ ----------------------------------------------------------------
```

**How to reproduce**  
1. Create a folder within `files` in the file manager of Contao and make it public.
2. Create the file `files/.public`.
3. Run `vendor/bin/contao-console contao:symlinks`.

**Ways to fix**
* Ignore `.public` files in the `files/` root.
* Or ignore `.public` files of sub folders, if the `files/` root already is `.public`.

I'd prefer the latter, since it's kind of a neat trick to be able to make Contao symlink the whole `files/` directory this way... ;). May be someone might need or want that...

**Comment by leofeyer** [comment]
Well, there are many ways to break the system if you manually do things you are not supposed to do. @contao/developers Do we really need to fix this?

**Comment by Toflar** [comment]
Imho the one directly in `files` should be forbidden because otherwise it's impossible to have private folders.

**Comment by mktcode** [comment]
https://github.com/contao/contao/blob/master/core-bundle/src/Command/SymlinksCommand.php#L264

![image](https://user-images.githubusercontent.com/6792578/51380611-66d35d00-1b12-11e9-92c5-060cd28855e1.png)

Already in place! Seems it just doesn't work for the root directory.

**Comment by mktcode** [comment]
@Toflar Everything is private by default. If someone decides to make the whole directory public... why not?
The backend could even offer that in the form of a checkbox. "Make all files public?"

**Comment by Toflar** [comment]
Because I think it's wrong :) Just add a folder named `public` and put all of the public stuff you want to make public in there. You never know what the future holds, at some point you suddenly need private data and then you have to move everything if you did not add a `public` folder in the first place. We should enforce best practice and making `files` public is definitely not a good practice.

**Comment by mktcode** [comment]
I don't think this is about right or wrong or best practices. It's just a matter of convenience in case a user wants the files directory to be public for whatever reason.

**Comment by Toflar** [comment]
Sure. I'll still give it a downvote.

**Comment by mktcode** [comment]
I'm just a friend of giving user's a choice and I don't understand your argument against it.

> "because otherwise it's impossible to have private folders"

Yes, of course... if you decide to make everything public, you'll not have private directories. If you want private directories, don't make everything public. But if you want everything to be public, why can't one checkbox be enough for that, instead of setting the flag every time  you create a new directory?

**Comment by m-vo** [comment]
Just create a subdirectory and set the flag there once? You'll probably need those anyways to distinguish between files that are mounted for certain backend users (e.g. content) and those that shouldn't (e.g. layout).

(Btw.: I'll usually just create the basic 'public structure' with .public files on the filesystem first (check these in as well) and then recreate the symlinks on deployment.)

**Comment by m-vo** [comment]
@fritzmg  Does the message from your initial post ("The path "web/files/public" exists and is not a symlink.") happen even though it's a symlink?

**Comment by fritzmg** [comment]
It's not a symlink anymore at that point. The path does not actually exist, so the error message is misleading.

**Comment by mktcode** [comment]
https://github.com/contao/contao/pull/288

This PR fixes the problem when having a `.public` file in the `files` directory AND in subdirectories. 

![image](https://user-images.githubusercontent.com/6792578/51386177-db61c800-1b21-11e9-92a7-c4b1be75a786.png)

**Comment by leofeyer** [comment]
Just to clarify: @Toflar's explanation in https://github.com/contao/contao/issues/286#issuecomment-455503554 is correct; the `files` directory is not meant to be made public.

**Comment by leofeyer** [comment]
Fixed in 02bebafb1f233b22e999a45e8bb9c5209e1805c2.

**Comment by xchs** [comment]
Unfortunately, for some reason, that doesn't seem to work anymore.

To reproduce (in Contao 4.4.40 and Contao 4.7.6):

- Create a file `.public` in the root files directory (i.e. `files/.public`)
- Open the _File manager_ and create a _New folder_
- The _Public_ checkbox is already selected (but grayed out)
- The folder icon still shows the lock indicator
- No symlink is created in `web/files` for the new folder (not even if you run the corresponding maintenance job)

**Comment by ausi** [comment]
As `files/.public` should not be supported, you have to remove the `.public` file to fix your issue I think.

**Comment by fritzmg** [comment]
But https://github.com/contao/contao/commit/02bebafb1f233b22e999a45e8bb9c5209e1805c2 should prevent that.

**Comment by xchs** [comment]
> As `files/.public` should not be supported, you have to remove the `.public` file to fix your issue I think.

Yeah, I know.

But that's exactly what this ticket here is about, i.e. Contao should actually ignore a `.public` file in the root files directory.
